title: About Me
author: Ritika
email: ritikasharmaatwork@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Know about the author's career milestones and current musings.

# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Ritikaa96 # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
